// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: UserCenterApiService.proto

package userCenterApi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserCenterApiClient is the client API for UserCenterApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCenterApiClient interface {
	Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userCenterApiClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCenterApiClient(cc grpc.ClientConnInterface) UserCenterApiClient {
	return &userCenterApiClient{cc}
}

func (c *userCenterApiClient) Login(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/userCenterApi.UserCenterApi/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCenterApiServer is the server API for UserCenterApi service.
// All implementations must embed UnimplementedUserCenterApiServer
// for forward compatibility
type UserCenterApiServer interface {
	Login(context.Context, *LoginParams) (*LoginResponse, error)
	mustEmbedUnimplementedUserCenterApiServer()
}

// UnimplementedUserCenterApiServer must be embedded to have forward compatible implementations.
type UnimplementedUserCenterApiServer struct {
}

func (UnimplementedUserCenterApiServer) Login(context.Context, *LoginParams) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserCenterApiServer) mustEmbedUnimplementedUserCenterApiServer() {}

// UnsafeUserCenterApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCenterApiServer will
// result in compilation errors.
type UnsafeUserCenterApiServer interface {
	mustEmbedUnimplementedUserCenterApiServer()
}

func RegisterUserCenterApiServer(s grpc.ServiceRegistrar, srv UserCenterApiServer) {
	s.RegisterService(&UserCenterApi_ServiceDesc, srv)
}

func _UserCenterApi_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCenterApiServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userCenterApi.UserCenterApi/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCenterApiServer).Login(ctx, req.(*LoginParams))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCenterApi_ServiceDesc is the grpc.ServiceDesc for UserCenterApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCenterApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userCenterApi.UserCenterApi",
	HandlerType: (*UserCenterApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserCenterApi_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UserCenterApiService.proto",
}
